spring:
  application:
    name: Payment


  datasource:
    url: jdbc:postgresql://localhost:5432/payment_demo
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

khalti:
    secret-key: YOUR_SECRET_KEY
    initiate-url: https://dev.khalti.com/api/v2/epayment/initiate/